import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import astro from 'eslint-plugin-astro'

export default tseslint.config(
  {
    ignores: [
      'dist',
      'node_modules',
      '.astro',
      // Wrangler's local dev scratch dir; gitignored, and its generated
      // no-op worker is not ours to lint.
      '.wrangler',
      '.lighthouse',
      'playwright-report',
      'test-results',
      // Vendored geometry, regenerated by scripts/sync-icons.mjs.
      'src/components/icons.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...astro.configs.recommended,

  {
    files: ['**/*.ts', '**/*.astro'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
    },
    rules: {
      // The site ships almost no client code; where it does, an implicit `any`
      // is how a DOM query silently returns the wrong thing.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  {
    // Build and audit scripts are Node, not browser.
    files: ['scripts/**/*.mjs', '*.config.{ts,mjs}', 'test/**/*.ts'],
    languageOptions: { globals: { ...globals.node } },
  },
)
