import { productLinks } from './product'

/**
 * Site-wide constants. `origin` is the ONE place the canonical host is
 * written; everything else derives from it, so a host change cannot leave a
 * stale absolute URL behind in a canonical, an OG tag or the sitemap.
 */
export const site = {
  origin: 'https://pixelferry.app',
  name: 'PixelFerry',
  /** Used as og:site_name and in the JSON-LD WebSite node. */
  shortDescription:
    'Batch image converter for macOS. Convert mixed HEIC, RAW, PSD, TIFF and WebP files in one pass, on your Mac.',
  locale: 'en',
  ogLocale: 'en_US',
  themeColor: '#090b12',
  /** 1200×630 render of the hero, regenerated by `scripts/make-og.mjs`. */
  ogImage: {
    path: '/og.jpg',
    type: 'image/jpeg',
    width: 1200,
    height: 630,
    alt: 'PixelFerry converting a queue of mixed image files on macOS.',
  },
} as const

/**
 * Build an absolute URL for a site-relative path.
 *
 * Canonicals, OG URLs and structured data must all be absolute and must all
 * agree; routing every one of them through here is what makes that provable
 * (`npm run audit:seo` asserts every canonical starts with `site.origin`).
 */
export function absoluteUrl(path: string): string {
  if (path === '/' || path === '') return `${site.origin}/`
  const clean = path.startsWith('/') ? path : `/${path}`
  // The site's trailing-slash policy is 'never' — production already redirects
  // `/privacy/` to `/privacy`, so a canonical must never carry one.
  return `${site.origin}${clean.replace(/\/$/, '')}`
}

/** Footer / nav destinations, in one place so nothing links to a dead route. */
export const navigation = {
  primary: [
    { label: 'Formats', href: '/formats' },
    { label: 'Conversions', href: '/convert' },
    { label: 'Guides', href: '/guides' },
  ],
  footer: [
    { label: 'Supported formats', href: '/formats' },
    { label: 'Conversions', href: '/convert' },
    { label: 'Guides', href: '/guides' },
    { label: 'Privacy policy', href: '/privacy' },
    { label: 'Cookie policy', href: '/cookies' },
    { label: 'Contact', href: `mailto:${productLinks.contactEmail}` },
  ],
} as const
